### ISSUE TITLE
Artifact not available for 2.13.0-M2

### ISSUE THREAD

**Issue by MasseGuillaume** [playframework/play-json#109]
Would it be possible to release play-json for 2.13.0-M2?

Thanks

**Comment by MasseGuillaume** [comment]
Blocked by:

https://github.com/scalatest/scalatest/issues/1189
https://github.com/etorreborre/specs2/issues/601

**Comment by MasseGuillaume** [comment]
Is it possible to cut a relase? It look like it's available since: https://github.com/playframework/play-json/commit/7f11fce165a418a393e1e532a3638786b3eb1d55.

Thanks.

**Comment by cchantep** [comment]
See #144

**Comment by MasseGuillaume** [comment]
Merci :-)
