### ISSUE TITLE
JSON readNullable erroneously fails with "error.path.empty"

### ISSUE THREAD

**Issue by gmethvin** [playframework/play-json#11]
**(Moved from playframework/playframework#6710)**

In Play 2.5 (and current master) the JSON readers for nullable types do not work when used without a nested path.

````scala
// works
val composableRootReadsNullableScoped: Reads[Root] = (
  (__ \ "foo").read[Foo] and
  (__ \ "bar").readNullable[Bar]
)((foo, barOpt) => Root(foo, barOpt.getOrElse(Bar(-1, -1, -1))))

// does not work
val composableRootReadsNullable: Reads[Root] = (
  (__ \ "foo").read[Foo] and
   __.readNullable[Bar]
)((foo, barOpt) => Root(foo, barOpt.getOrElse(Bar(-1, -1, -1))))
````

using the following JSON inputs
````json
// for first reader
{
  "foo": { "a": 1, "b": 0 },
  "bar": {
    "barA": 0,
    "barB": 0,
    "barC": 0
  }
},

// for second reader
{
  "foo": { "a": 1, "b": 0 },
  "barA": 0,
  "barB": 0,
  "barC": 0
}
````

I expect both examples to result in the same parsed `Root` object containing the same `Foo` and `Bar`. The use-case of handling several fields with their own specialised `Reads` seems very natural to me. Often API's contain rows which are multiple merged objects like bar and foo in this example, and composing the combined `Reads` using other `Reads` is the nicest solution in my opinion.

For all types & a test case, see my full example:
https://gist.github.com/hermanbanken/98057a12f349ddbc6fab9575b8aa5f2e

````
[error] Actual:   JsError(List((,List(ValidationError(List(error.path.empty),WrappedArray())))))
[error] Expected: JsSuccess(Root(Foo(1,0),Bar(0,0,0)),)
````

The JsError originates in [JsPath.scala#L184](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-json/src/main/scala/play/api/libs/json/JsPath.scala#L184). I'm not sure, but maybe the branch checking Nil is unnecessary? Nil is a valid tail, so maybe it should be handled as a empty tail?

**Comment by asheshambasta** [comment]
Just bumped into the same issue. What's the ETA on this please?

**Comment by hermanbanken** [comment]
Huray 👍
