### ISSUE TITLE
Scala.js compiler crash when using macro api

### ISSUE THREAD

**Issue by yoo-haemin** [playframework/play-json#116]
### Play JSON Version
2.6.5

### API
scala-js

### Operating System
* Ubuntu 16.04 (Linux hostname 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
* macOS Sierra

### JDK
* `openjdk version "1.8.0_131"` on Ubuntu
* Oracle JVM 1.8.0_141 on Mac (As far as I remember; I don't use a Mac anymore)

### Library Dependencies
Nothing other than play-json and scala-js itself

### Expected Behavior
1. Create an ADT (`sealed trait` hierarchy)
2. Create `Format` instances of the case classes by calling `Json.format[Class]` respectively, and have them in the implicit scope
3. Call `Json.format[Trait]`
4. `Format[Trait]` should have been created by macros

### Actual Behavior
Compiler crash. Additional details are available [here](https://github.com/scala-js/scala-js/issues/3144).

### Reproducible Test Case
I have a separate [repo](https://github.com/yoo-haemin/scalajs-bugreport).

**Comment by cchantep** [comment]
As indicated in the details, the bug occurs in Json macro, but the cause is that the compilation gives an invalid symbol name at first.

A workaround can be added, anyway would be useful to understand by the name is not valid at first.

**Comment by cchantep** [comment]
Considering that w/o Scala.JS there is no issue, it doesn't seem related : https://github.com/cchantep/scalajs-bugreport/tree/without_scalajs

**Comment by cchantep** [comment]
A workaround is now on master (investigating why compiler with JS interop give such invalid owner name).
