### ISSUE TITLE
Json.writes derivation fails to support simple case classes

### ISSUE THREAD

**Issue by fommil** [playframework/play-json#117]
```scala
import play.api.libs.json._

final case class EventDeserializationFailure(cause: String)
object EventDeserializationFailure {
  implicit val writes: Writes[EventDeserializationFailure] = Json.writes
}
```

fails with

```
[error] No apply function found for scala.Any
[error]     implicit val writes: Writes[EventDeserializationFailure] = Json.writes
[error]                                                                     ^
```

using play 2.6.6 on scala 2.12.4

**Comment by fommil** [comment]
it seems that the type is required on the RHS, but this is not the case for `Json.format` and it makes it very hard to automate the generation of these implicits.

**Comment by cchantep** [comment]
I don't see how any function, macro or not, could have its tparam properly infered.

BTW what's the issue in calling as documented with `= Json.format[T]` instead of such `: T = Json.format` (in both case the type is specified, verbosity seems the same to me).

**Comment by fommil** [comment]
It works for every other macro I've seen, it also works for format. Who knows the way of the compiler.

The reason I don't simply add the type to the RHS is because this is called from generated code that works across a wide variety of generic derivation macros. Many of those derivers take more than one type parameter (e.g. shapeless generics). I'd rather write a new generic derivation using a non-macro approach than special case this, so that's on my plan.

**Comment by cchantep** [comment]
Which macro is working this way? I'd guess it requires some extra/aux implicit instances or conversions ...

**Comment by fommil** [comment]
the play-json `Json.format` works with the type on the left, as do all shapeless based generic derivations (they typically have a lot of type parameters to do the `.Aux` hack).

**Comment by cchantep** [comment]
I don't get what you mean ...

**Comment by fommil** [comment]
```
import play.api.libs.json._

final case class EventDeserializationFailure(cause: String)
object EventDeserializationFailure {
  implicit val format: Format[EventDeserializationFailure] = Json.format
}
```

works. The problem is in the `writes` macro.

**Comment by cchantep** [comment]
`Writes` is contravariant

**Comment by fommil** [comment]
I don't see why variance should affect type inference. Actually it's quite bad that Writes is contravariant... don't you know about the contrarivariant implicit search bug in scala? https://issues.scala-lang.org/browse/SI-2509 there is an easier version proposed by paul phillips

```scala
scala> :paste
       trait Thing[-A]
       def f(x: Thing[ Seq[Int]]): Byte   = 1
       def f(x: Thing[List[Int]]): Short  = 2

scala> f(new Thing[ Seq[Int]] { })
       f(new Thing[List[Int]] { })

res = 1
res = 2

scala> :paste
       implicit val t1: Thing[ Seq[Int]] =
         new Thing[ Seq[Int]] { override def toString = "1" }
       implicit val t2: Thing[List[Int]] =
         new Thing[List[Int]] { override def toString = "2" }

scala> implicitly[Thing[ Seq[Int]]]
       implicitly[Thing[List[Int]]]

res = 1
res = 1

```

**Comment by cchantep** [comment]
Yes I'm thinking of that known [blight of contrarivariance](https://groups.google.com/forum/#!topic/scala-language/ZE83TvSWpT4), and yes personally. I would tend to remove such contravariance,
