### ISSUE TITLE
Build JsPath from raw string

### ISSUE THREAD

**Issue by fmeriaux** [playframework/play-json#138]
Is there a way to build a `JsPath` from a raw string ?

Example : 

From `"/foo/bar"` get `JsPath \ "foo" \ "bar"`

Is it conceivable to support this, if it is not already the case ?

If so, it would also be interesting to have a format to read / write a path.

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question/for help. Best regards.

**Comment by fmeriaux** [comment]
Is not just a question/for help it's a feature proposal (to my knowledge nonexistent).

Example: From an string `/foo/bar` get `JsPath \ "foo" \ "bar"`

**Comment by cchantep** [comment]
Even feature request should first go first on the mailing list to be discussed before any action.

**Comment by fmeriaux** [comment]
Just search JsPath in the mailing list to realize that several requests have been made about it without any response.

I thought that an issue would make more visibility to a requested feature, but if that bothers you, you can close that issue.

**Comment by cchantep** [comment]
The tracker is for actionnable ticket, confirmed issue or already discussed feature request. Best regards.
