### ISSUE TITLE
Feature request: add new typeclass for json key encode

### ISSUE THREAD

**Issue by xuwei-k** [playframework/play-json#166]
add new typeclass like `argonaut.EncodeJsonKey`, `io.circe.KeyEncoder`? WDYT?

- https://github.com/circe/circe/blob/v0.9.3/modules/core/shared/src/main/scala/io/circe/KeyEncoder.scala
- https://github.com/argonaut-io/argonaut/blob/v6.2.2/argonaut/shared/src/main/scala/argonaut/EncodeJsonKey.scala

**Comment by cchantep** [comment]
Not sure what you mean, there is already `JsonNaming` used with macro conversions.

**Comment by cchantep** [comment]
Closing it for now.

**Comment by xuwei-k** [comment]
`JsonNaming` is different feature.

play-json `Writes[Map[K, V]]` instance Key type restricted only `String`. but argonaut and circe is not only String.

https://github.com/playframework/play-json/blob/33558cbe8238db6c1bea98c6b9af348ddcabaee9/play-json/shared/src/main/scala/play/api/libs/json/Writes.scala#L264

- https://github.com/argonaut-io/argonaut/blob/v6.2.2/argonaut/shared/src/main/scala/argonaut/EncodeJson.scala#L160
- https://github.com/circe/circe/blob/a2d5b4b733c96bdcafd81a76713a7aed4f61b30f/modules/core/shared/src/main/scala/io/circe/Encoder.scala#L396-L413

**Comment by cchantep** [comment]
I can see the use case with a `Map[K, V]`, but not in other.
