### ISSUE TITLE
Commit release version to README.md

### ISSUE THREAD

**Issue by aaabramov** [playframework/play-json#175]
If would we awesome if sbt release process will have additional step with modifying README with latest version before commiting version changes.

As an example we can take: https://github.com/bot4s/telegram/blob/master/project/TelegramBot4sRelease.scala

**Comment by plokhotnyuk** [comment]
BTW, jsoniter-scala already do it before committing of released version, fill free to adopt it for your release process: https://github.com/plokhotnyuk/jsoniter-scala/blob/master/release.sbt#L4-L15

**Comment by aaabramov** [comment]
@plokhotnyuk nice, in telegram4s it is achieved using _sbt-release_ plugin without explicitly using `git` executable

**Comment by plokhotnyuk** [comment]
@aaabramov could you, please, point which option of its _build.sbt_ toggle it? 
Just wondering if it capable to update version in badge links, etc.

**Comment by aaabramov** [comment]
@plokhotnyuk could you clarify your question, please?
By using [this](https://github.com/bot4s/telegram/blob/master/project/TelegramBot4sRelease.scala) example we can update everything that we need by matching RegExps in ReadME.
