### ISSUE TITLE
Move documentation in the separate repo

### ISSUE THREAD

**Issue by cchantep** [playframework/play-json#19]
So it can be updated along/as soon as the code is updated

**Comment by gmethvin** [comment]
There are several pages in the Play Framework documentation we could potentially move over in some form:
 - https://www.playframework.com/documentation/2.6.x/ScalaJson
 - https://www.playframework.com/documentation/2.6.x/ScalaJsonAutomated
 - https://www.playframework.com/documentation/2.6.x/ScalaJsonCombinators
 - https://www.playframework.com/documentation/2.5.x/ScalaJsonTransformers
 
The following are specific to Play Framework and would have to be separated in some way:
 - https://www.playframework.com/documentation/2.6.x/ScalaJsonHttp

We can continue to use omnidoc and publish with the Play Framework documentation, or we could place the Play JSON docs somewhere else.

One thing that's different here from other libraries we've split out is that there are inter-dependencies between the Play Framework docs and JSON docs. So we have may to change up how we do the doc validation and external documentation references as well.

**Comment by gmethvin** [comment]
Fixed by #37
