### ISSUE TITLE
getOrElse argument could to be lazy to match with Option.getOrElse

### ISSUE THREAD

**Issue by jankeesvanandel** [playframework/play-json#20]
Hi,

First of all, Happy New Year to you all and thanks for all your efforts on this project!

Second, I ran into an issue today, where I tried the following code:
`val structureId = (json \ "id").getOrElse(sys.error(s"Cannot find 'id' property in SessieOverview JSON: $json"))`

But I didn't get the behaviour I expected from getOrElse (the same behaviour as Option.getOrElse), which is that the parameter to getOrElse is lazy. In my case, the parameter is evaluated eagerly, which resulted in an exception (I know I'm not being purely functional here, but in general I think it's good practice to evaluate the else part lazily, since that corresponds with the "else" keyword).

Could you change this line in:
`def getOrElse(v: JsValue): JsValue = toOption.getOrElse(v)`

into:
`@inline def getOrElse(v: => JsValue): JsValue = toOption.getOrElse(v)`

Much appreciated!

Regards,
Jan-Kees

**Comment by cchantep** [comment]
Hi,

It seems to me that [`JsLookup.getOrElse`](https://github.com/playframework/play-json/blob/master/play-json/src/main/scala/play/api/libs/json/JsLookup.scala#L107) and [`JsResult.getOrElse`](https://github.com/playframework/play-json/blob/master/play-json/src/main/scala/play/api/libs/json/JsResult.scala#L132) are already lazy on master.

**Comment by jankeesvanandel** [comment]
Ah, nice! Now I see it was added in 2.5.10 (and this project is still on 2.4):
https://github.com/playframework/playframework/commit/b628ecfee85490097e88be4be263f3119141d73a

**Comment by cchantep** [comment]
Fine. @gmethvin / @wsargent could you close this one (I don't have permission on this repo). Thx

**Comment by gmethvin** [comment]
@cchantep you should have permission on this repo now
