### ISSUE TITLE
Performance: JsUndefined is very slow

### ISSUE THREAD

**Issue by npeters** [playframework/play-json#203]
JsUndefined is very slow, especially when the json is big.
The problem comes from this two pieces of code 

```scala
final class JsUndefined(err: => String) extends JsLookupResult {
  def error = err
  def validationError = JsonValidationError(error)
  override def toString = s"JsUndefined($err)"
}
```
```scala
case class JsonValidationError(messages: Seq[String], args: Any*) {
  lazy val message = messages.last
}

object JsonValidationError {
  def apply(message: String, args: Any*): JsonValidationError =
    JsonValidationError(Seq(message), args: _*)
}
```
JsonValidationError evaluates message, but message can be very big and long to evaluate: especially on this case 
```scala
/**
   * Return the property corresponding to the fieldName, supposing we have a JsObject.
   *
   * @param fieldName the name of the property to look up
   * @return the resulting JsValue wrapped in a JsLookup. If the current node is not a JsObject or doesn't have the
   *         property, a JsUndefined will be returned.
   */
  def \(fieldName: String): JsLookupResult = result match {
    case JsDefined(obj @ JsObject(_)) =>
      obj.value.get(fieldName).map(JsDefined.apply)
        .getOrElse(JsUndefined(s"'$fieldName' is undefined on object: $obj"))
    case JsDefined(o) =>
      JsUndefined(s"$o is not an object")
    case undef => undef
  }
```

when the field is not found, the message contains all the JsObject and must serialize and concat to the string and it can be very slow.

I'm really open to discuss about a solution.

**Comment by npeters** [comment]
It is link to #110

**Comment by plokhotnyuk** [comment]
@npeters please look into [sources] (https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/MissingReqFieldBenchmark.scala)  and [results] (http://jmh.morethan.io/?source=https://plokhotnyuk.github.io/jsoniter-scala/oraclejdk11.json) of `MissingRequiredFieldBenchmark`. This comparison of how the missing field is handled by different JSON parsers can inspire you a lot.
