### ISSUE TITLE
Enhance json example

### ISSUE THREAD

**Issue by aaabramov** [playframework/play-json#239]
We can improve [validation pattern matching](https://www.playframework.com/documentation/2.6.x/ScalaJson#Using-validation) example a bit:

    val nameResult: JsResult[String] = (json \ "name").validate[String]

    // Pattern matching
    nameResult match {
      case s: JsSuccess[String] => println("Name: " + s.get)
      case e: JsError => println("Errors: " + JsError.toJson(e).toString())
    }

With this:

    val nameResult: JsResult[String] = (json \ "name").validate[String]

    // Pattern matching
    nameResult match {
      case JsSuccess(name) => println("Name: " + name)
      case e: JsError => println("Errors: " + JsError.toJson(e).toString())
    }

What do you think, community?

**Comment by marcospereira** [comment]
I'm transferring this to play-json since it is where the documentation lives. :-)

**Comment by aaabramov** [comment]
@marcospereira I am open to contribution, as always. Could you point me where I need to make changes?

Because link for contribution on site points to nowhere: 
https://github.com/playframework/playframework/edit/2.6.x/documentation/manual/working/scalaGuide/main/json/ScalaJson.md

**Comment by aaabramov** [comment]
@marcospereira seems that exactly this one is already fixed: https://github.com/playframework/play-json/blob/master/docs/manual/working/scalaGuide/main/json/code/ScalaJsonSpec.scala#L344
