### ISSUE TITLE
why does play json losses precision while reading/parsing?

### ISSUE THREAD

**Issue by sashasami03** [playframework/play-json#241]
In the following example (scala 2.11 and play-json 2.13)

`val j ="""{"t":2.2599999999999997868371792719699442386627197265625}"""
println((Json.parse(j) \ "t").as[BigDecimal].compare(BigDecimal("2.2599999999999997868371792719699442386627197265625")))`

The output is -1. Shouldn't they be equal ? On printing the parsed value, it prints rounded off value:

`println((Json.parse(j) \ "t").as[BigDecimal]) gives 259999999999999786837179271969944`

**Comment by sashasami03** [comment]
Following the solution here as of now: https://stackoverflow.com/questions/55208230/why-does-play-json-lose-precision-while-reading-parsing

ie. System.setProperty("play.json.parser.mathContext", "unlimited")

**Comment by plokhotnyuk** [comment]
@sashasami03 BEWARE! Do not use "unlimited" if your systems are opened to the wide wild world.

Source of the problem which was resolved by introducing default rounding to "decimal128" is that current implementation of parsing the decimal string representation to `BigDecimal` or `BigInt` has O(n^2) complexity:

```
scala> def timed[A](f: => A): A = { val t = System.currentTimeMillis; val r = f; println(s"Elapsed time (ms): ${System.currentTimeMillis - t}"); r }
timed: [A](f: => A)A

scala> timed(BigInt("9" * 1000000))
Elapsed time (ms): 13151

scala> timed(BigDecimal("9" * 1000000))
Elapsed time (ms): 13165
```

For current 1Gb network 10ms of receiving a malicious message with a 1M digit number can produce 1300ms of CPU load in a one core. More than 100 cores can be effectively DoS at a full bandwidth rate.

Also lot of arithmetic operations has O(n^1.5) complexity, even such a "safe" operations as `+` for not validated scale of input can much more powerfull bomb to blowout your JVM by a single message:

```
scala> timed(BigDecimal("9e-999999"))
Elapsed time (ms): 0

scala> timed(BigDecimal("9e-9999999") + 1)
Elapsed time (ms): 3055
```

So, feel free to keep the current answer to be accepted or investigate deeply and write a real answer to your question...

**Comment by sashasami03** [comment]
Thanks plokhotnyuk. For the time I have moved away from play Jon for deserializing BigDecimal.
