### ISSUE TITLE
Optional reads if any part of the path is not present

### ISSUE THREAD

**Issue by jroper** [playframework/play-json#268]
Consider the following:

```
scala> (__ \ "a" \ "b").readNullable[String].reads(Json.obj("a" -> Json.obj()))
res1: play.api.libs.json.JsResult[Option[String]] = JsSuccess(None,)

scala> (__ \ "a" \ "b").readNullable[String].reads(Json.obj())
res2: play.api.libs.json.JsResult[Option[String]] = JsError(List((/a/b,List(JsonValidationError(List(error.path.missing),WrappedArray())))))
```

This is kind of surprising to me - since I would expect the above to behave the same as this, which it doesn't:

```
scala> (Json.obj() \ "a" \ "b").validateOpt[String]
res3: play.api.libs.json.JsResult[Option[String]] = JsSuccess(None,)
```

I'm not sure if there's a good reason why `readNullable` only returns a `JsSuccess(None)` if the last part of the path is missing, but fails for the rest. If there is a good reason, then it would be nice to have a version of it that would return `JsSuccess(None)` if any part of the path is missing. My use case for this is when you're only interested in a few small parts of a deeply nested object structure, so you want to extract out those few fields without having to incrementally `readNullable` each part of the path and then `flatMap` the reads (which ends up becoming very unreadable very quickly).

**Comment by jroper** [comment]
Here's an example implementation of what I want, not sure about naming:

```scala

  private implicit class JsPathReadOptIfMissing(path: JsPath) {
    def readOptIfMissing[T: Reads]: Reads[Option[T]] = Reads { jsValue =>
      path.asSingleJson(jsValue) match {
        case JsDefined(value) => value.validate[T].map(Some.apply)
        case JsUndefined() => JsSuccess(None)
      }
    }
  }
```

**Comment by lforite** [comment]
I ran into the same issue and the default behaviour is indeed surprising

**Comment by jroper** [comment]
PR raised: #302.
