### ISSUE TITLE
play.libs.Json is missing in M2

### ISSUE THREAD

**Issue by wsargent** [playframework/play-json#36]
The play.libs.Json package is missing in M2

Play-WS depends on M1 right now, but upgrading to M2 breaks it:

https://github.com/playframework/play-ws/blob/master/project/Dependencies.scala#L16

See:

https://github.com/playframework/play-ws/blob/master/play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSRequest.java#L24

**Comment by wsargent** [comment]
Also see https://github.com/scala/community-builds/issues/471#issuecomment-278760627

**Comment by gmethvin** [comment]
`play.libs.Json` is a very thin wrapper for Jackson, and was removed from Play JSON since Play JSON is a Scala library.

Instead of using a static `ObjectMapper`, I'd suggest adding a dependency on a Jackson `ObjectMapper`, or maybe an `ObjectWriter`.

**Comment by cchantep** [comment]
Couldn't the `Json` companion (the one in `api.json`) be used instead? From what I see the requirement of PlayWS would match `.toBytes`.

**Comment by gmethvin** [comment]
For the WS Java API we need to convert a Jackson `JsonNode` to bytes. Looks like all we are doing is calling `ObjectMapper#writeValueAsBytes`.
