### ISSUE TITLE
JsObject should return immutable collections (play-json 2.8/ scala 2.13)

### ISSUE THREAD

**Issue by 987Nabil** [playframework/play-json#388]
I was just migrating to scala 2.13 and realised, that the only collections related migration I had to do, was with JsObject. I was using this two fields

```
  /**
   * The fields of this JsObject in the order passed to the constructor
   */
  lazy val fields: collection.Seq[(String, JsValue)] = underlying.toSeq

  /**
   * The value of this JsObject as an immutable map.
   */
  lazy val value: Map[String, JsValue] = underlying match {
    case m: immutable.Map[String, JsValue] => m
    case m                                 => m.toMap
  }
```

What I found interesting is, that even the second comment says `immutable map` and `underlying.toSeq` is returning an `immutable.Seq` the return values are `collection.Map`and `collection.Seq`. This seems odd to me. Especially because immutable collections should be considered the default, since it is what is defined in predef now (2.13).

Are there any good reasons to not change this to immutable?

**Comment by 14mr0n** [comment]
After checking out play json, I realized that `underlying.toSeq` is not returning an immutable collection.
But values for sure is always immutable and I don't see any harm in the type being more restrictive/concrete.


So my suggestion would be
```
  /**
   * The value of this JsObject as an immutable map.
   */
  lazy val value: immutable.Map[String, JsValue] = underlying match {
    case m: immutable.Map[String, JsValue] => m
    case m                                 => m.toMap
  }

  /**
   * Return all fields as a set
   */
  def fieldSet: immutable.Set[(String, JsValue)] = fields.toSet
```

**Comment by renatocaval** [comment]
This is a backwards-incompatible change. The way to go here is to add new variants that are immutable and deprecate the mutable ones. 

So, ok for `fieldSet`. But `value` must stay what it is and instead we need a new variant, eg: `valueMap` or `asMap`.  

`valueMap` aligns well with `fieldSet`

**Comment by renatocaval** [comment]
@14mr0n, forgot to mention. PRs are super welcome! 😉

**Comment by 14mr0n** [comment]
@renatocaval thanks for clarification. I'll happily do this changes and open a PR in the next days. :)

**Comment by asazernik** [comment]
I might also jump on this when/if my workload permits.

**Comment by RichardMarto** [comment]
Any updates on this issue? I'm able to fix it right now if needed.

**Comment by octonato** [comment]
@RichardMarto no updates and I don't think anyone is working on it. Feel free to pick. 

Let me know if you do it so I assign to you just to signal to others that someone is already on it.

**Comment by RichardMarto** [comment]
I'm just not sure about which version should be in `since` argument on `@deprecated()`, should I use the next minor version? Where can I find more about how this project is versioned?

**Comment by RichardMarto** [comment]
Is there any documentation that needs to be updated?
The tests that already exist should be enough for these changes, right?
Was I right to assume 2.9.3 as the version in which value will be deprecated?

**Comment by RichardMarto** [comment]
I think I misunderstood something. `fieldSet` should be ignored, deprecated or just changed?
I thought that it should be changed, but it was also a backward-incompatible change.

**Comment by johnduffell** [comment]
This also affects JsError and other in this file due to this import, would be great to have it fixed:
https://github.com/playframework/play-json/blob/f1769bd5a3dd98e41ecdad6bf67cb86021f601fd/play-json/shared/src/main/scala/play/api/libs/json/JsResult.scala#L7
