### ISSUE TITLE
Make Json.reads macro handle case class default params gracefully

### ISSUE THREAD

**Issue by gmethvin** [playframework/play-json#4]
**(Moved from playframework/playframework#3244)**

It would be nice if `Json.reads` was able to synthesize `Reads` classes for `case class`s with default parameter values. So riffing on the example, we might have:

``` scala
case class Person(name: String, age: Int, lovesChocolate: Boolean, favoriteColor: String = "blue")

implicit val personReads = (
  (__ \ 'name).read[String] and
  (__ \ 'age).read[Int] and
  (__ \ 'lovesChocolate).read[Boolean] and
  ((__ \ 'favoriteColor).read[String] orElse Reads.pure("blue"))
)(Person)
```

(I imagine, there's probably some non-trivial reflection needed to get the default parameter value.)

Perhaps of interest to @mandubian

**Comment by andyglow** [comment]
Hello, guys!
I have added a possible solution and I would like to have some feedback and wondering if it might be merged. Thanks!

**Comment by fancywriter** [comment]
Hi @gmethvin!
Is it already in 2.6.0, as far as I understand?

**Comment by fancywriter** [comment]
Hi @gmethvin , @andyglow 
I have tested it and actually it doesn't give me behaviour I expected.
```
import play.api.libs.json._

case class Foo(s: String = "default value")
implicit val format": Format[Foo] = Json.using[Json.WithDefaultValues].format[Foo]

println(Json.obj().validate[Foo])
// JsSuccess(Foo(default value),) <- OK
println(Json.obj("s" -> "overridden value").validate[Foo])
// JsSuccess(Foo(overriden value),) <- OK 
println(Json.obj("s" -> 100).validate[Foo])
// JsSuccess(Foo(default value),) <- NOT OK
println(Json.obj("s" -> Json.obj("foo" -> Json.arr("bar"))).validate[Foo])
// JsSuccess(Foo(default value),) <- NOT OK at all
```

It gives default value for any type of error - however, I expect to see it only for missing value or for null (it field is not Option of course, in this case I expect to see None for JsNull and error for everything else).

```
case class Foo(s: Option[String] = Some("default some"))

println(Json.obj().validate[Foo])
// JsSuccess(Foo(Some(default some)),)
println(Json.obj("s" -> JsNull).validate[Foo])
// works as expected JsSuccess(Foo(None),)
println(Json.obj("s" -> 100).validate[Foo])
// is fine too, by the way, gives JsError(List((/s,List(JsonValidationError(List(error.expected.jsstring),WrappedArray())))))
```

**Comment by gmethvin** [comment]
Yes, the problem is fixed here: https://github.com/playframework/play-json/pull/121

There are concerns about breaking old behavior, though I'm pretty convinced the current behavior doesn't make sense since it's inconsistent with how it works for optional fields, where the default is only used for nonexistent values and not for errors.

**Comment by fancywriter** [comment]
Awesome, I think this issue can be closed, what do you think?

**Comment by TimMoore** [comment]
This capability was added in #17 but is undocumented, so difficult for people to discover.

**Comment by gmethvin** [comment]
closing this. thanks @dontgitit!

**Comment by TimMoore** [comment]
Still would be nice to document this :smile:
