### ISSUE TITLE
Support for Javascript JSON Number

### ISSUE THREAD

**Issue by maxifom** [playframework/play-json#439]
I recently had a problem with that JSON more than Javascript’s Number.MAX_SAFE_INTEGER (2^53-1) get’s truncated because in Scala it’s marshalled to JSON as integer value. I’m suggesting to add a flag to JSON parser/serializer to add functionality of converting integers > 2^53-1 to string for better javascript compatibility. 
P.S I forked and added this functionality myself for my personal use, but I’m open to your views on this option.

**Comment by dhoepelman** [comment]
I'd recommend against writing out number as JSON strings or numbers depending on their size, that's a recipe for bugs with large numbers in the consumers.
If you want to write out all numbers as string always you can overwrite the default `Writes[BigDecimal]`/:

```
implicit val stringNumberWrites: Writes[BigDecimal] = Writes.of[String].contraMap[BigDecimal](_.toString)
```

I suggest closing as wontfix.
