### ISSUE TITLE
play-json 3.0.0

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-json#463]
Because of #449 and #450 bumping Jackson to 2.11.0 next version released from `master` should be `play-json:3.0.0`.

If improvements on the `2.8.x` family are required a stable branch should be created before the jackson version was bumped (or in `HEAD` and then downgrade the Jackson version in the stable branch).

**Comment by ennru** [comment]
Let's revert the Jackson upgrades and see if we can release 2.8.x via tags on master.

**Comment by ennru** [comment]
The Jackson updates were reverted in the merge from 2.8.x and we now released 2.9.0 from master.
The Jackson libraries are pinned to 2.10.x for Scala Steward.

Play JSON 3.0 is in far distance...
