### ISSUE TITLE
NullPointerException with Writes.contramap

### ISSUE THREAD

**Issue by dhpiggott** [playframework/play-json#51]
I have a project where I made this change:
```
-    Writes(
-      a => Writes.of[Seq[Either[JsonRpcNotificationMessage, JsonRpcRequestMessage]]].writes(a.messages)
-    )
+    Writes
+      .of[Seq[Either[JsonRpcNotificationMessage, JsonRpcRequestMessage]]]
+      .contramap(_.messages)
   )
```

That change works just fine.

I also made this change:
```
-    Writes(
-      a => Writes.of[Seq[JsonRpcResponseMessage]].writes(a.messages)
-    )
+    Writes
+      .of[Seq[JsonRpcResponseMessage]]
+      .contramap(_.messages)
```

That results in a NullPointerException when running the tests:
```
[info]   - should encode to [{"jsonrpc":"2.0","result":{"param1":"param1","param2":"param2"},"id":1}] *** FAILED ***
[info]     java.lang.NullPointerException:
[info]     at play.api.libs.json.LowPriorityWrites.$anonfun$traversableWrites$2(Writes.scala:267)
[info]     at play.api.libs.json.LowPriorityWrites$$Lambda$2412/520876750.apply(Unknown Source)
[info]     at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[info]     at scala.collection.TraversableLike$$Lambda$95/1119390268.apply(Unknown Source)
[info]     at scala.collection.immutable.List.foreach(List.scala:378)
[info]     at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[info]     at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[info]     at scala.collection.immutable.List.map(List.scala:284)
[info]     at play.api.libs.json.LowPriorityWrites.$anonfun$traversableWrites$1(Writes.scala:267)
[info]     at play.api.libs.json.LowPriorityWrites$$Lambda$2161/1735133288.apply(Unknown Source)
[info]     ...
```

The full reproducible test case is an open pull request at https://github.com/dhpcs/scala-json-rpc/pull/19/files.

The test failure can be seen in the build log at https://travis-ci.org/dhpcs/scala-json-rpc/builds/210733337.

I've spent a couple of hours trying to figure out the root cause (mostly by looking at the stack in IntelliJ when it fails to see what is null) but have not reached any conclusion yet and am starting to doubt that I will. If it is that I've misunderstood something and the issue is with what I have done, it's certainly not obvious to me, so I thought it better that I open this issue in case this really is a play-json bug.

The issue isn't critical because I already have something that works. I just ran into this while tidying it up, and it does _seem_ like it could be a play-json issue.

### Configuration

play-json version: Replicated with 2.5.13 and 2.6.0-M5
API: Replicated with Scala 2.11.8 and 2.12.1
Library dependencies: ScalaTest 3.0.1

OS and JVM:

Replicated on `Ubuntu 16.04.2 (Linux ash 4.8.0-42-generic #45~16.04.1-Ubuntu SMP Thu Mar 9 14:10:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)` with
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
and on macOS 10.12 with
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by gmethvin** [comment]
@dhpiggott It looks like this is because your implicit `Writes[JsonRpcResponseMessage]` is not initialized (null) at the time your `Writes[JsonRpcResponseMessageBatch]` is constructed. I didn't try to figure out why exactly, but I confirmed this is the case by adding an assert to the `JsonRpcMessageBatch` object:

```scala
 assert(Writes.of[JsonRpcResponseMessage] != null)
```

The assertion fails when I run the tests. So this is not a bug in Play JSON.

You may just want to declare all your formats as `lazy val` so you don't have to worry about circular dependency issues when initializing your objects.

**Comment by dhpiggott** [comment]
Thanks for the pointer @gmethvin. I should have been able to get that far myself - sorry for opening the ticket a bit early. My only defence is that it was late and the end of a long day!

I see now that `Writes.of[JsonRpcResponseMessage] == null`.

That's certainly a step closer to understanding the root cause.

However, what I find strange is that after adding two more asserts, I see that only `Writes.of[JsonRpcResponseMessage]` is null. `JsonRpcResponseMessage.JsonRpcResponseMessageFormat` is initialized correctly, and `Reads.of[JsonRpcResponseMessage]` resolves correctly. It's only the Writes that resolves to null.

This (unsurprisingly) is also the case if I remove the use of contramap, reverting to the working `JsonRpcResponseMessageBatchFormat` definition, the third assertions fails in the following, but the writes itself works correctly when the assertion that prevents the test running is removed:
```
object JsonRpcResponseMessageBatch {
  assert(JsonRpcResponseMessage.JsonRpcResponseMessageFormat != null)
  assert(implicitly[Reads[JsonRpcResponseMessage]] != null)
  assert(implicitly[Writes[JsonRpcResponseMessage]] != null)
  implicit final val JsonRpcResponseMessageBatchFormat: Format[JsonRpcResponseMessageBatch] = Format(
    Reads
      .of[Seq[JsonRpcResponseMessage]](verifying(_.nonEmpty))
      .map(JsonRpcResponseMessageBatch(_)),
    Writes(
      a => Writes.of[Seq[JsonRpcResponseMessage]].writes(a.messages)
    )
  )
}
```

Given this, I wouldn't expect that making all the format instances lazy vals would actually help. However, I tried it anyway, and it may be interesting to note that doing so results in the following stackoverflow:

```
An exception or error caused a run to abort. 
java.lang.StackOverflowError
	at scala.collection.mutable.ListBuffer.$plus$eq(ListBuffer.scala:44)
	at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:59)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:182)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
	at scala.collection.generic.GenericCompanion.apply(GenericCompanion.scala:49)
	at play.api.libs.json.JsonValidationError$.apply(JsonValidationError.scala:12)
	at play.api.libs.json.ConstraintReads.verifying(JsConstraints.scala:157)
	at play.api.libs.json.ConstraintReads.verifying$(JsConstraints.scala:156)
	at play.api.libs.json.Reads$.verifying(Reads.scala:74)
	at com.dhpcs.jsonrpc.JsonRpcResponseMessageBatch$.JsonRpcResponseMessageBatchFormat$lzycompute(JsonRpcMessage.scala:336)
	at com.dhpcs.jsonrpc.JsonRpcResponseMessageBatch$.JsonRpcResponseMessageBatchFormat(JsonRpcMessage.scala:334)
	at com.dhpcs.jsonrpc.JsonRpcMessage$.JsonRpcMessageFormat$lzycompute(JsonRpcMessage.scala:79)
	at com.dhpcs.jsonrpc.JsonRpcMessage$.JsonRpcMessageFormat(JsonRpcMessage.scala:75)
	at com.dhpcs.jsonrpc.JsonRpcResponseMessageBatch$.JsonRpcResponseMessageBatchFormat$lzycompute(JsonRpcMessage.scala:339)
	at com.dhpcs.jsonrpc.JsonRpcResponseMessageBatch$.JsonRpcResponseMessageBatchFormat(JsonRpcMessage.scala:334)
	at com.dhpcs.jsonrpc.JsonRpcMessage$.JsonRpcMessageFormat$lzycompute(JsonRpcMessage.scala:79)
	at com.dhpcs.jsonrpc.JsonRpcMessage$.JsonRpcMessageFormat(JsonRpcMessage.scala:75)
	at com.dhpcs.jsonrpc.JsonRpcResponseMessageBatch$.JsonRpcResponseMessageBatchFormat$lzycompute(JsonRpcMessage.scala:339)
	at com.dhpcs.jsonrpc.JsonRpcResponseMessageBatch$.JsonRpcResponseMessageBatchFormat(JsonRpcMessage.scala:334)
...
```

So the closest I can get is thinking that the key is in the fact that:

1. Only `implicitly[Writes[JsonRpcResponseMessage]] == null` (but `implicitly[Reads[JsonRpcResponseMessage]] != null)`

2. `implicitly[Writes[Either[JsonRpcNotificationMessage, JsonRpcRequestMessage]] != null`.

3. This works:
   ```
   Writes(
     a => Writes.of[Seq[JsonRpcResponseMessage]].writes(a.messages)
   )
   ```

4. This does not:
   ```
   Writes
     .of[Seq[JsonRpcResponseMessage]]
     .contramap(_.messages)
   ```

5. And yet this combination of the two does work:
   ```
   Writes(
     a =>
       Writes
         .of[Seq[JsonRpcResponseMessage]]
         .contramap[JsonRpcResponseMessageBatch](_.messages)
         .writes(a)
   )
   ```

For the above three points, when I say "works" or "does not", I mean that it either functions as expected or throws a NullPointerException. Specifically it's because of `val w = implicitly[Writes[A]]` on line 265 of `Writes.scala` having resolved to null:
```
sealed trait LowPriorityWrites extends EnvWrites {
  /**
   * Serializer for Traversables types.
   */
  implicit def traversableWrites[A: Writes] = {
    val w = implicitly[Writes[A]]

    Writes[Traversable[A]] { as => JsArray(as.map(w.writes(_)).toSeq) }
    // Avoid resolution ambiguity with more specific Traversable Writes,
    // such as OWrites.map
  }
}
```

**Comment by gmethvin** [comment]
If you look at the stack trace it's appears that `JsonRpcResponseMessageBatchFormat` depends on `JsonRpcMessageFormat`, which in turn depends on `JsonRpcResponseMessageFormat`. So there is a cyclic dependency.

The reason it works when you use `Writes { a => ... }` is because that block is not evaluated until the `Writes` is used, so `JsonRpcMessageFormat` is already initialized at that point.

Now, you may ask: why is it using `JsonRpcMessageFormat`, a `Format[JsonRpcMessage]`, when I need an implicit `Format[JsonRpcResponseMessage]`? The answer has to do with the fact that `Writes[-A]` is contravariant. This means Scala considers the supertype "more specific" than the subtype for implicit resolution. This behavior is a bit strange, and is reported as a Scala bug: https://issues.scala-lang.org/browse/SI-2509

Unfortunately it is also somewhat useful that `Writes` is contravariant, so it would be hard to change in Play JSON without breaking a lot of people's code.

If you want to pick up the `JsonRpcResponseMessageFormat`, you can add a local import so it picks that one:
```scala
// to prevent cyclic dependency on JsonRpcMessageFormat chosen by implicit resolution
import JsonRpcResponseMessage.JsonRpcResponseMessageFormat

implicit lazy val JsonRpcResponseMessageBatchFormat: Format[JsonRpcResponseMessageBatch] = Format(
  Reads
    .of[Seq[JsonRpcResponseMessage]](verifying(_.nonEmpty))
    .map(JsonRpcResponseMessageBatch(_)),
  Writes.of[Seq[JsonRpcResponseMessage]].contramap(_.messages)
)
```

Even if you resolve this, you're still probably better off using `lazy val`s in the future since the stack trace will tell you where to find the cyclic dependencies instead of just getting a `NullPointerException`.

**Comment by dhpiggott** [comment]
I see! Thanks so much for investigating and for the explanation. It's all clear now. I'd completely failed to spot that `JsonRpcMessageFormat` was being used. I've gone ahead with both your suggestions - adding the local import, and switching to `lazy vals`.

**Comment by Reeebuuk** [comment]
Had the same issue and it helped me as well :) Thx guys!
