### ISSUE TITLE
Scala 2.12 version

### ISSUE THREAD

**Issue by olegstepura** [playframework/play-json#53]
Hi!

Is it planned to release 2.12 version any time soon? It is blocking https://github.com/eclipsesource/play-json-schema-validator/issues/83

If I try to force use 2.11 version in `sbt` I get conflicting cross-version suffixes for `org.scalaz:scalaz-core` `_2.11`, `_2.12` since some lib already uses `scalaz-core`

**Comment by xuwei-k** [comment]
http://repo1.maven.org/maven2/com/typesafe/play/play-json_2.12/

**Comment by olegstepura** [comment]
Thanks! Closing this.
