### ISSUE TITLE
Publish for Scala 3.0.0-RC1?

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-json#570]
#571 will need to land first

**Comment by dwijnand** [comment]
@ennru with #571 do you fancy cutting another RC with this?

I'm separately working on resolving the blocker that will allow us to release it as non-RC (the fully-qualified classname issue @jtjeferreira took issue with).

**Comment by dwijnand** [comment]
> I'm separately working on resolving the blocker that will allow us to release it as non-RC (the fully-qualified classname issue @jtjeferreira took issue with).

https://github.com/playframework/play-json/pull/572

**Comment by ennru** [comment]
Published 2.10.0-RC2 https://github.com/playframework/play-json/releases/tag/2.10.0-RC2
