### ISSUE TITLE
Rework publishing to not use Bintray

### ISSUE THREAD

**Issue by ennru** [playframework/play-json#578]
The current publishing process uses Bintray as an intermediate step before the artefacts reach Maven Central.
With Bintray going away this needs to be changed.

**Comment by RichardMarto** [comment]
Sonatype still offers nexus repository OSS. Outside of the repository itself, there are any other requirements?

**Comment by SethTisue** [comment]
I suggest we switch to sbt-ci-release (which uses sbt-sonatype).

Is there a project-wide discussion about this? We should go with whatever the rest of playframework/* is doing unlesss there's a special reason not to.

**Comment by SethTisue** [comment]
I would like to publish play-json for Scala 3.0.0-RC3, which is out now (though we should wait for ScalaTest to publish).

So if there aren't any objections, I'll go ahead with sbt-ci-release on Wednesday if there aren't any objections.

**Comment by SethTisue** [comment]
fixed by #603 — but I'll need @ennru (or somebody) to add the Sonatype publishing secrets to the repo

**Comment by ennru** [comment]
@octonato agreed to help here.
