### ISSUE TITLE
Play-json should be able to read java.time.Instant instances in the default readers

### ISSUE THREAD

**Issue by kraythen** [playframework/play-json#59]
Currently the user has to implement java.time.* classes themselves but they have been in since JDK 1.8. I would propose the following: 

```scala
  implicit val jsonWritesInstant: Writes[Instant] = {
    case i: Instant => JsString(ISO_INSTANT.format(i))
    case null => JsNull
  }

  implicit def jsonReadsInstant: Reads[Instant] = Reads[Instant] {
    case JsString(n) =>
      try {
        JsSuccess(Instant.from(ISO_INSTANT.parse(n)))
      } catch {
        case e: DateTimeParseException => JsError("error.invalid.dateformat")
      }
    case JsNull => JsSuccess(null)
    case _ => JsError("error.expected.string")
  }
```

The only downside i can see is that it would bind the lib to jdk8. Possibly could be an add on module for jdk8?

**Comment by gmethvin** [comment]
We already support `Instant`, in addition to many other `java.time` types: https://github.com/playframework/play-json/blob/2.6.0-M6/play-json/jvm/src/main/scala/play/api/libs/json/EnvReads.scala#L415

**Comment by kraythen** [comment]
Hmm I looked and didn't see this.  Much appreciated. Nevermind, closing.
