### ISSUE TITLE
Publish for Scala 3.0.0-RC3

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-json#600]
blocked for now by #578, but I aim to unblock that this week.

**Comment by SethTisue** [comment]
progress: #599 is merged, #602 is merged, and there is a draft PR reworking publishing at #503 but it isn't done. I will have to return to this in a few more day

**Comment by SethTisue** [comment]
#603 is ready for merge

**Comment by SethTisue** [comment]
#603 is merged

**Comment by SethTisue** [comment]
Renato has added the secrets

I pulled the publishing lever at https://github.com/playframework/play-json/releases/tag/2.10.0-RC3

release job: https://travis-ci.com/github/playframework/play-json/jobs/503995463

aaaaaaaaaand it didn't work: `No access to secret variables, doing nothing`

@octonato comparing what I see at https://github.com/playframework/play-json/settings/secrets/actions to the instructions at https://github.com/olafurpg/sbt-ci-release , I noticed that `PGP_PASSPHRASE` is missing?

but I think that's not the proximate cause of the failure, because that wouldn't make the check at https://github.com/olafurpg/sbt-ci-release/blob/main/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L29-L32 fail . I suspect the proximate cause is that the secrets are in the "Actions secrets" section of https://github.com/playframework/play-json/settings/secrets/actions rather than the "Repository secrets", but we are releasing via Travis-CI, not GitHub Actions. @octonato does that seem plausible to you?

**Comment by avdv** [comment]
AFAIK, secrets on Github are only usable within Github Actions. If you're releasing via Travis CI, you need to provide your secrets over there. 

Looking forward to the release... :smiley:

**Comment by SethTisue** [comment]
> If you're releasing via Travis CI, you need to provide your secrets over there

Oh, ha, of course!

@octonato it's here the secrets are needed: https://travis-ci.com/github/playframework/play-json/settings

**Comment by octonato** [comment]
🤦 , of course. That's it. 

Sorry for the confusion. We have been moving things from Travis to GH Actions and at the same time updating the publishing. I didn't realise that this one was still using Travis.

**Comment by octonato** [comment]
@SethTisue, the `PGP_PASSPHRASE` is only required with you add a password to the PGP secret.

**Comment by SethTisue** [comment]
I re-ran the publishing job and it seems to have worked this time.

Closing this one; 3.0.0 is next: https://github.com/playframework/play-json/issues/612

**Comment by SethTisue** [comment]
I seem to have been confused somehow. The job is re-running now at https://travis-ci.com/github/playframework/play-json/builds/225334149

**Comment by SethTisue** [comment]
the release job eventually failed with `2021-05-13 23:06:04.193Z error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.play is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:425)`

@octonato what do we do next?

**Comment by avdv** [comment]
> the release job eventually failed with `2021-05-13 23:06:04.193Z error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.play is not found. Check your sonatypeProfileName setting in build.sbt - (Sonatype.scala:425)`

Seems like the sonatype account used when publishing has no publishing rights for the com.typesafe[.play] organization. You probably need to create a Jira ticket to request access to that organization...

Just my 2¢.

**Comment by octonato** [comment]
I initially configured with the credentials we use for Akka. However, I just changed it to the credentials we had in Vegemite (old build machine we had) and it didn't work. 

I will need to look at that in more detail. I have no idea why it's not working.

**Comment by octonato** [comment]
I may have made a mistake on my previous run. 

I just got play-ebean published using the vegemeite credentials: 
https://travis-ci.com/github/playframework/play-ebean/jobs/507725920

**Comment by raul782** [comment]
Hi @octonato, is there something we could help here?

**Comment by octonato** [comment]
Unfortunately not. Someone with access to the credentials will need to jump in. 
I could get back to it and I don't think I will have time this week. Maybe next week, but I can't promise.

**Comment by raul782** [comment]
Thanks for the update. @SethTisue is there someone that could help on this, as avdv mentioned. If there is a different Sonatype account that is being used, It wouldn't hurt to open a Jira Ticket to request permissions to publish on com.typesafe.play organization. I can see similar issues in jira like this one: https://issues.sonatype.org/browse/OSSRH-56740

**Comment by mblund** [comment]
@SethTisue or @octonato any updates on this? I'm sorry but I cannot contribute with anything else than cheering and :partying_face: for this. I would love to get this and #612 Publish for Scala 3.0.0 ready, to be able to try out scala 3 in our own projects.

**Comment by SethTisue** [comment]
I don't think there's any point now in publishing for 3.0.0-RC3, so I'm going to close this one and let's continue on #612
