### ISSUE TITLE
Publish for Scala 3.0.0

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-json#612]
* [x] fix PR validation builds
* [x] merge outstanding PRs
* [x] choose version number
  * 2.10.0-RC5 — I deleted the RC3 and RC4 tags since they didn't publish, but I'm reluctant to reuse even an unreleased version number, so let's call it RC5
* [x] fix publishing (need help from @octonato or somebody else at Lightbend)
* [x] tag it
* [x] wait for release job
  * https://travis-ci.com/github/playframework/play-json/builds/232868402
* [x] wait for artifacts to hit Maven Central
  * https://repo1.maven.org/maven2/com/typesafe/play/play-json_3/2.10.0-RC5/

**Comment by SethTisue** [comment]
status: as discussed at #600, I need help from @octonato or somebody else at Lightbend before I can pull publishing levers

**Comment by SethTisue** [comment]
@marcospereira hey Marcos, Renato is unavailable for the next two weeks. is there any possibility you could step in here...?

**Comment by xuwei-k** [comment]
any updates? 👀

**Comment by SethTisue** [comment]
Marcos and I now have an appointment on Thursday to try and straighten this out.

**Comment by SethTisue** [comment]
Just to recap where things stand, the last publishing effort was https://travis-ci.com/github/playframework/play-json/jobs/503995463 which failed with `2021-05-25 11:35:25.673Z error [Sonatype] [MISSING_PROFILE] Profile com.typesafe.play is not found. Check your sonatypeProfileName setting in build.sbt  - (Sonatype.scala:425)
1295`

**Comment by SethTisue** [comment]
current hypothesis is that #642 will fix it

**Comment by SethTisue** [comment]
2.10.0-RC5 is published. Please report any problems!
