### ISSUE TITLE
Branding and versioning

### ISSUE THREAD

**Issue by gmethvin** [playframework/play-json#63]
Seeing as how this library is no longer a part of the play release cycle, and is meant to be used outside Play, is it worth rebranding it using a new name?

If we change the artifact name we can also change the versioning scheme with minimal confusion.

**Comment by gmethvin** [comment]
@leonardehrenfried Independent releases are already happening, btw. We just haven't changed the versioning scheme.

**Comment by SethTisue** [comment]
I suggest we close this — the name is too well established, and the current pace of development is slow.
