### ISSUE TITLE
Binary compatibility is broken between 2.9.3 & 2.10.0-RC6

### ISSUE THREAD

**Issue by t3hnar** [playframework/play-json#798]
```scala
def example(a: JsValue): Option[Boolean] = a match {
      case JsBoolean(a) => Some(a)
      case _ => None
}
```

fails at runtime with

```
java.lang.NoSuchMethodError: 'scala.Option play.api.libs.json.JsBoolean$.unapply(play.api.libs.json.JsBoolean)'
```

Here is problematic commit:

https://github.com/playframework/play-json/commit/9a13cc1a21b9321a3dbe9cefcba161096da1b19c#diff-69c77ca2160f8159a7712f4fe94ce07e3e27b762e222c8204bfbbc05124d02efR77

**Comment by t3hnar** [comment]
> Actually we don't guarantee binary compatibility between 2.9.x and 2.10.x
that is a very surprising statement… especially in scope of current problem, when this is not a necessary change and can be really easily avoided.


Could you please reconsider this and maybe fix, or at least… are you will to accept MR with the fix?

**Comment by plokhotnyuk** [comment]
W/A is replacing `case JsBoolean(a) => Some(a)` by `case a: JsBoolean => Some(a.value)`

**Comment by t3hnar** [comment]
@plokhotnyuk sure, that does work as mitigation after you already got an error :)

**Comment by mkurz** [comment]
If you provide a pull request and it passes CI tests, we can think about what to do. Looking at the commit and its PR it looks like this was done for Scala 3 compatibility. We build/test against Scala 3 already, so we will see.

**Comment by plokhotnyuk** [comment]
Yet another W/A would be migration to jsoniter-scala. It provides backward binary compatibility for minor versions. Also, it is much handy in derivation and more efficient in runtime (sometime in more than 10x times ;)
![image](https://user-images.githubusercontent.com/890289/195313917-48174a4e-34a2-4569-8397-4d552e98abf6.png)
![image](https://user-images.githubusercontent.com/890289/195313764-086050b1-51b5-46fd-b697-feb45d26b2fa.png)
For more results using 16 threads see: https://plokhotnyuk.github.io/jsoniter-scala/index-t16.html

**Comment by OlegYch** [comment]
@plokhotnyuk this was fixed but not yet released https://github.com/playframework/play-json/issues/767

**Comment by mkurz** [comment]
Ahh, nice, I overlooked that, I can release a new version...

**Comment by OlegYch** [comment]
@mkurz please do

**Comment by mkurz** [comment]
Actually do you think we can release that as 2.10.0 final? It seems people use it already and in the main branch I started to pull in a unstable 2.9. milestone already... So I don't want to release from the current HEAD of main actually...
@OlegYch WDYT? I think I will branch of a 2.10.x branch , release RC7 and if that there are no issues reported we can cut a 2.10 final soon.

**Comment by OlegYch** [comment]
@mkurz sounds good
i'm concerned about dropping java8 though, that's a big change...

**Comment by mkurz** [comment]
I would not drop Java 8 for a 2.10 release. I would branch off not from the main HEAD but somewhere before and revert some commits so it stays compatible with RC6.

**Comment by OlegYch** [comment]
ah, ok

**Comment by mkurz** [comment]
2.10.0-RC7 released: https://github.com/playframework/play-json/releases/tag/2.10.0-RC7
Please test this version, I will promote it to final release if everything is ok.
