### ISSUE TITLE
`JsBoolean` on Scala 3: `productElementNames` throw an java.lang.IndexOutOfBoundsException: 0 exception

### ISSUE THREAD

**Issue by arturaz** [playframework/play-json#859]
### Play JSON Version (2.5.x / etc)

2.10.0-RC6+225

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Not applicable.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Not applicable.

### Expected Behavior

```scala
import play.api.libs.json.*

try { 
  // This throws an `java.lang.IndexOutOfBoundsException: 0` exception.
  // It should not
  JsFalse.productElementNames.toVector
}
catch { case t =>
  t.printStackTrace()
}
```

https://scastie.scala-lang.org/qNqSm2IgTPaMrfSFfY5i8w

### Resolution

Providing this in `JsBoolean` fixes the problem:
```scala
  // A fix for https://github.com/lampepfl/dotty/issues/17146
  override def productElementName(n: Int): String =
    if (n == 0) "value" else throw new IndexOutOfBoundsException(s"Index out of range: $n")
```

However, that breaks cross-compilation as `productElementName` needs to be an `override` in some Scala versions and not the others and the only way to resolve that issue that I know is to make separate versions of `JsValue` for all needed Scala versions :|

Also see https://github.com/lampepfl/dotty/issues/17146

**Comment by mkurz** [comment]
@xuwei-k or @cchantep do you want to take a look?

**Comment by xuwei-k** [comment]
I propose we just remove deprecated `JsBoolean` methods. it's 6 years ago https://github.com/playframework/play-json/commit/534ddb830f45848666a4b1a20d0bfc3de3692839#diff-0738c782ad0b47514ae6e6217101115e98d38bcef24995817eee365f5a0e0fc2R39

**Comment by xuwei-k** [comment]
- https://github.com/playframework/play-json/pull/861
