### ISSUE TITLE
New release for play-json that updates jackson-databind version

### ISSUE THREAD

**Issue by tal181** [playframework/play-json#872]
Hi,
Are there any plans to release a new version of play-json that includes an update to jackson-databind version (>2.14.0)?
jackson-databind has a high security vulnerability and I see that the Main branch was already updated.

Thanks
Tal

**Comment by mkurz** [comment]
We will soon release new versions of Play and play-json with latest versions of jackson.
For now you should be able to upgrade jackson yourself in your applications, please see https://github.com/orgs/playframework/discussions/11222

**Comment by tal181** [comment]
Hi @mkurz do you have an ETA ?

**Comment by mkurz** [comment]
The ETA for a new Play release should be very soon, hopefully at least an RC at beginning of May. Still waiting on the Scala 3.3.0 final / 2.13.11 release.

**Comment by mkurz** [comment]
2.10.0 released, coming with Jackson 2.14.3:
https://github.com/playframework/play-json/releases/tag/2.10.0
