### ISSUE TITLE
wrong implicit resolution

### ISSUE THREAD

**Issue by MasseGuillaume** [playframework/play-json#88]
```scala
import play.api.libs.json._

def dontSerialize[T](fallback: T): Format[T] = new Format[T]{
  def writes(v: T): JsValue = JsNull
  def reads(json: JsValue): JsResult[T] = JsSuccess(fallback)
}
def dontSerializeOption[T]: Format[Option[T]] = dontSerialize(None)

// Does not compile
case class Fur()
case class Foo(v: Option[Fur])
implicit val dontSerializeFur: Format[Option[Fur]] = dontSerializeOption[Fur]
implicit val formatFoo = Json.format[Foo]


// Workarround
case class Fur2()
type OFur2 = Option[Fur2]
case class Foo2(v: OFur2)
implicit val dontSerializeFur: Format[OFur2] = dontSerializeOption[Fur2]
implicit val formatFoo = Json.format[Foo2]
```

**Comment by cchantep** [comment]
Hi,

In such case the details of the error is useful:

```
error: No instance of play.api.libs.json.Format is available for scala.Option[Fur] in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
       implicit val formatFoo = Json.format[Foo]
```

> As indicated in the [guide](https://github.com/playframework/play-json/blob/master/.github/ISSUE_TEMPLATE.md), please note that this tracker is for confirmed issue. Rather use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask question/for help.

It happens that:

1. The case class `Fur` as-is doesn't make sense, without any property (either at least one property or a `case object`).
2. A `Format[Fur]` is not provided, whereas required to resolve the missing `Format[Option[Fur]]`.

e.g.:

```scala
import play.api.libs.json._

def dontSerialize[T](fallback: T): Format[T] = new Format[T]{
  def writes(v: T): JsValue = JsNull
  def reads(json: JsValue): JsResult[T] = JsSuccess(fallback)
}
def dontSerializeOption[T]: Format[Option[T]] = dontSerialize(None)

// Does not compile
case class Fur(v: Int)
implicit val requiredFormat: Format[Fur] = Json.format[Fur]
case class Foo(v: Option[Fur])
implicit val dontSerializeFur: Format[Option[Fur]] = dontSerializeOption[Fur]
implicit val formatFoo = Json.format[Foo]
```

**Comment by MasseGuillaume** [comment]
1. Edited to make it obvious what Fur is: ThisIsNotSerializable

```
import play.api.libs.json._

def dontSerialize[T](fallback: T): Format[T] = new Format[T]{
  def writes(v: T): JsValue = JsNull
  def reads(json: JsValue): JsResult[T] = JsSuccess(fallback)
}
def dontSerializeOption[T]: Format[Option[T]] = dontSerialize(None)


class ThisIsNotSerializable()
case class Foo(v: Option[ThisIsNotSerializable])
implicit val dontSerializeFur: Format[Option[ThisIsNotSerializable]] = dontSerializeOption[ThisIsNotSerializable]
implicit val formatFoo = Json.format[Foo]
```

2. Reported error:
```
No instance of play.api.libs.json.Format is available for scala.Option[Playground.ThisIsNotSerializable] in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
```

**Comment by cchantep** [comment]
... and so ? The error makes sense for me.

Please use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask question/for helper.

**Comment by MasseGuillaume** [comment]
are you sure ?

```scala
implicit val dontSerializeFur: Format[Option[ThisIsNotSerializable]] = dontSerializeOption[ThisIsNotSerializable]
```

`No instance of play.api.libs.json.Format is available for scala.Option[Playground.ThisIsNotSerializable]`

**Comment by cchantep** [comment]
The macros are automatically managing `Option`al case class properties, provided that for a property whose type is `Option[T]` there are typeclass (`Writes` and/or `Reads`) for `T`.

Overriding the automatic support of `Option`al is not supported (as be error prone).

Either use the macro in this way, or you need to manage the whole format manually.

> Please use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask question/for helper.

**Comment by MasseGuillaume** [comment]
Well it's supported, here is a counter example:

```scala
import play.api.libs.json._

def dontSerialize[T](fallback: T): Format[T] = new Format[T]{
  def writes(v: T): JsValue = JsNull
  def reads(json: JsValue): JsResult[T] = JsSuccess(fallback)
}
def dontSerializeOption[T]: Format[Option[T]] = dontSerialize(None)

class ThisIsNotSerializable()
type WorkArround = Option[ThisIsNotSerializable]
case class Foo(v: WorkArround, field1: Int, field2: Int)
implicit val dontSerializeFur: Format[WorkArround] = dontSerializeOption[ThisIsNotSerializable]
implicit val formatFoo = Json.format[Foo]
```

**Comment by cchantep** [comment]
Because the alias prevent it (probably a missing `.dealias`), anyway the expected behaviour is the automatic one.

**Comment by julienrf** [comment]
Still, I think the error message is incorrect. What’s missing is a `Format[ThisIsNotSerializable]` (as opposed to a `Format[scala.Option[Playground.ThisIsNotSerializable]]`, like the error message says)

**Comment by cchantep** [comment]
Message is updated in #89
