### ISSUE TITLE
new RC pubished for Scala 3.3.0

### ISSUE THREAD

**Issue by pjfanning** [playframework/play-json#884]
Would it be possible to get a 2.10 RC published that uses Scala 3.3.0 instead of Scala 3.3.0-RC5? I'm trying to get a Pekko Connector upgraded to support Scala3 - and it uses play-json as a test dependency.

https://mvnrepository.com/artifact/com.typesafe.play/play-json_3/2.10.0-RC8

fyi @mkurz

**Comment by mkurz** [comment]
Will do this evening.

**Comment by pjfanning** [comment]
One quick question. play-json seems to only support Java 11+. Is that something that is planned generally across Play Framework?

**Comment by mkurz** [comment]
Yes. Play 2.9 will drop Java 8. Only supported versions will be 11 and 17 and very likely 21 in September (all the LTS ones).

**Comment by mkurz** [comment]
I postponed that to today, I had a look yesterday evening, there is some mess with the branches. Was to tired for sane work. I ping you later.

**Comment by pjfanning** [comment]
Thanks @mkurz. I was able to work around my problem. So this is not urgent for me.

**Comment by mkurz** [comment]
FYI I did publish RC9 yesterday evening.
