### ISSUE TITLE
json.Json.format does not work with -Yno-predef

### ISSUE THREAD

**Issue by fommil** [playframework/play-json#92]
If a project has

```
scalacOptions += "-Yno-predef"
```

it will be unable to use the `Json.format` (and related) macros because they expand to use symbols that are not imported, such as `scala.Predef.implicitly`.

The fix is pretty simple (and good practice in macros) which is to use `_root_.`-qualified FQNs for all symbols in the macro (thereby not making any assumptions about the caller's scope).

This is a regression from play 2.5... I assume the macro has changed.

**Comment by fommil** [comment]
in fact it looks like some of the other play-json typeclasses are being referenced in the expanded macro too, assuming that the package is imported perhaps.

**Comment by cchantep** [comment]
Would be nice to add the exact error details, as indeed the macros are using `val libs = q"_root_.play.api.libs"` as base `Tree` to generate the type references.

**Comment by fommil** [comment]
ok, I'll try to get a typer print from next time I see this.

**Comment by cchantep** [comment]
Close it for now. Let reopen if there is anything new.

**Comment by fommil** [comment]
awesome, thanks! I wasn't expecting this to be closed and it was a nice surprise to see it in the latest release :smile:
