### ISSUE TITLE
json.Json.format does not support case object

### ISSUE THREAD

**Issue by fommil** [playframework/play-json#93]
this is the upstream bug for https://github.com/fommil/stalactite/issues/14

I've created a macro that makes it a lot easier to derive typeclasses with semi-auto derivation. But it seems that `.format` does not support `case object`, requiring special handling. I'd like you to consider supporting `case object` in your macro to avoid the need for special casing in stalactite. Everything based on shapeless derivation is able to support `case object` as a product alongside `case class`es, so I think play-json is the odd one out.

**Comment by cchantep** [comment]
Hi,

What would be expected as JSON representation in such case? An empty `{}` JSON object I guess? If so the priority of such feature would be quite low for me.

Would at least need a prio discussion on the [MailingList](https://groups.google.com/forum/#!forum/play-framework) before it could be in any way be actionable.

Best regards

**Comment by fommil** [comment]
yes, empty is what I always do. But there is merit in duplicating the name again.

**Comment by cchantep** [comment]
The object name would make sense, but in a sealed family, not alone.

**Comment by fommil** [comment]
I've seen all kinds of weird uses where have the name makes sense, usually bad API design. That said, I prefer empty.

**Comment by gmethvin** [comment]
I think an empty object makes sense, but then it's pretty easy to duplicate the behavior without a macro:

```scala
def formatEmpty[A](thunk: => A): Format[A] = new Format[A] {
  def reads(json: JsValue) = thunk
  def writes(o: A) = JsObject.empty
}
```

Then use `formatEmpty(CaseObject)` to get a format for your case object that serializes to `{}`

**Comment by richdougherty** [comment]
If we want it to be a bit more efficient then I'd suggest `null` instead of an empty object. Using `null` will be easier to parse and won't take as much space in an AST.

**Comment by fommil** [comment]
surely you mean `JsNull` and `()`?

**Comment by jroper** [comment]
I recommend using an object, either empty, or with a property in it that contains the name.

The reason for this is that if in future, you change it to something that contains a field, you end up with a nice clean migration path (old code ignores the field, new code can mark the field as an option or have a default value).

In Lagom, where we use play-json for persistence and for serialization of commands over Akka remoting, we also offer migrations which take the JsObject and transform it before deserialization is done. This works best when what is being worked with is an object.

**Comment by fommil** [comment]
Yeah that's clean, and consistent with other product types.

**Comment by fommil** [comment]
w00t!
