### ISSUE TITLE
toJson does not always preserve the order of elements in collection

### ISSUE THREAD

**Issue by t3hnar** [playframework/play-json#95]
### Play Version 2.6.3

I found that `LowPriorityWrites.traversableWrites` does not always preserve the order.
For instance we have `scala.collection.mutable.SortedSet` of elements, however json has wrong output because of `as.map(w.writes(_))`
I suppose it should be something like `as.toSeq.map(w.writes(_)`

### Expected Behavior

```
Json.toJson(scala.collection.mutable.SortedSet(1, 2, 3)) = [1, 2, 3]
```

### Actual Behavior

```
Json.toJson(scala.collection.mutable.SortedSet(1, 2, 3)) = [2,1,3]
```

**Comment by gmethvin** [comment]
It's broken with immutable sets too:

```scala
Json.toJson(scala.collection.mutable.SortedSet(1, 2, 3, 4, 5))
// [4,1,3,5,2]
```

Since we are building an array here, maybe the most efficient way is to create an `ArrayBuilder` and just iterate through the original set and add elements. Since `traversableWrites` is commonly used it could be a significant performance gain as well.

**Comment by t3hnar** [comment]
just link the original post https://github.com/playframework/playframework/issues/7750

**Comment by t3hnar** [comment]
> Since we are building an array here, maybe the most efficient way is to create an ArrayBuilder and just iterate through the original set and add elements.

yes, that is a very good idea
